# Circle CI configuration file
# /project/target/challenge-0.0.1-SNAPSHOT.jar
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/project

    steps:
      - checkout:
          path: ~/project
      - run:
          name: Build
          command: mvn -B clean package
      - store_artifacts:
          path: ~/project/target
      - store_test_results:
          path: ~/project/target/surefire-reports

workflows:
  app:
    jobs:
      - build