# Circle CI configuration file
# /project/target/challenge-0.0.1-SNAPSHOT.jar
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/project

    steps:
      - checkout:
          path: ~/project
      - run:
          name: Build
          command: mvn -B clean package
      - run:
          name: Artifact
          command: |
            mkdir /tmp/artifacts;
            cp ~/project/target/*.jar /tmp/artifacts;
          when: on_fail
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  app:
    jobs:
      - build